export enum ExceptionEnum {
  BadRequestException = 'BadRequestException',
  UnauthorizedException = 'UnauthorizedException',
  NotFoundException = 'NotFoundException',
  ForbiddenException = 'ForbiddenException',
  NotAcceptableException = 'NotAcceptableException',
  RequestTimeoutException = 'RequestTimeoutException',
  ConflictException = 'ConflictException',
  GoneException = 'GoneException',
  HttpVersionNotSupportedException = 'HttpVersionNotSupportedException',
  PayloadTooLargeException = 'PayloadTooLargeException',
  UnsupportedMediaTypeException = 'UnsupportedMediaTypeException',
  UnprocessableEntityException = 'UnprocessableEntityException',
  InternalServerErrorException = 'InternalServerErrorException',
  NotImplementedException = 'NotImplementedException',
  ImATeapotException = 'ImATeapotException',
  MethodNotAllowedException = 'MethodNotAllowedException',
  BadGatewayException = 'BadGatewayException',
  ServiceUnavailableException = 'ServiceUnavailableException',
  GatewayTimeoutException = 'GatewayTimeoutException',
  PreconditionFailedException = 'PreconditionFailedException',
}
